name: Playwright Tests
run-name: ${{ github.actor }} is learning Github Actions
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        cd ..
        python3 -m venv venv
        source venv/bin/activate
        pip install -U pip setuptools
        pip install -e .
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    - name: Run your tests
      run: pytest rozenka/tests/
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-traces
        path: test-results/
