name: Playwright Tests
run-name: ${{ github.actor }} is learning Github Actions
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '>=3.8.7'
    - name: Install env dependencies
      run: |
        python3 -m venv venv/
        source venv/bin/activate
        pip install -U pip setuptools
        pip install -e .
        playwright install --with-deps
    - name: Run your tests
      run: |
        source venv/bin/activate 
        pytest --browser firefox --browser chromium